values:
  appName: "web-demo"
  image:
    repository: "nginx"
    tag: "latest"
    digest: ""
    pullPolicy: "IfNotPresent"
  service:
    port: 80
  replicas: 2
  env:
    - name: "ENV"
      value: "production"
  message: "Hello, World!"